name: Sync module  for Surge
on:
  workflow_dispatch:
  schedule:
    - cron: "20 23 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Sync module and js  on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "siri_sg=https://raw.githubusercontent.com/VirgilClyne/iRingo/main/sgmodule/Siri.sgmodule" >> $GITHUB_ENV
          echo "youtube_sg=https://raw.githubusercontent.com/Maasea/sgmodule/master/YouTube.Enhance.sgmodule" >> $GITHUB_ENV
          echo "spotify_sg=https://raw.githubusercontent.com/app2smile/rules/master/module/spotify.module" >> $GITHUB_ENV
        shell: bash

      - name: Checkout the default branch
        uses: actions/checkout@v4

      - name: Make directory
        run: |
          mkdir -p ruleset
          mkdir -p js_new

      - name: Sync `basename ${siri_sg}` file
        run: |
          curl -sSL ${siri_sg} > ruleset/`basename ${siri_sg}`

      - name: Sync `basename ${youtube_sg}` file
        run: |
          curl -sSL ${youtube_sg} > ruleset/`basename ${youtube_sg}`

      - name: Sync `basename ${spotify_sg}` file
        run: |
          curl -sSL ${spotify_sg} > ruleset/`basename ${spotify_sg}`
          mv ruleset/spotify.module ruleset/spotify.sgmodule

      - name: Git push assets to "main" branch
        run: |
          mv ruleset/*  modules
          jsnames=$(grep path= modules/* | awk -F "script-path=" '{print $2}'| awk -F "," '{print $1 }' |sort | uniq)
          for jsfile in ${jsnames}; do curl -sSL ${jsfile} > js_new/`basename ${jsfile}`; done
          for jsfile in ${jsnames}; do sed -i "s|${jsfile}|https://raw.githubusercontent.com/killua525/surge/main/js/`basename ${jsfile}`|g" modules/*; done
          mv js_new/* js
          rm -rf ruleset js_new
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.name "github-actions[bot]"
            git config --local user.email "91898282+github-actions[bot]@users.noreply.github.com"
            git add js modules
            git commit -m "${{ env.RELEASE_NAME }}"
            git push
            echo "name=committed::true" >> $GITHUB_OUTPUT
          else
            echo "name=committed::false" >> $GITHUB_OUTPUT
          fi





